version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

build:
  commands:
    - python -m pip install --upgrade "setuptools>=68" "packaging>=23.0"
