coord_policy:
    always:
        cls: AlwaysPolicy
        agent: 'weak'
    threshold:
        cls: ThresholdPolicy
        metric: 'logit'
    random:
        cls: RandomPolicy
        baseline: False
    ppo:
        cls: PPOPolicy
    ood:
        cls: OODPolicy
coord_env:
    procgen:
        strong_query_cost_ratio: 0.4
        switch_agent_cost_ratio: 0.0
        act_greedy: False
    cliport:
        strong_query_cost_ratio: 0.4
        switch_agent_cost_ratio: 0.0
        act_greedy: False
    minigrid:
        strong_query_cost_ratio: 0.4
        switch_agent_cost_ratio: 0.0
        act_greedy: False
evaluation:
    procgen:
        validation_episodes: 256
        test_episodes: 256
        act_greedy: False
    cliport:
        validation_episodes: 64
        test_episodes: 64
        act_greedy: False
    minigrid:
        validation_episodes: 256
        test_episodes: 256
        act_greedy: False
environment:
    procgen:
        common:
            env_name: 'coinrun'
            normalize_rew: False
            num_envs: 64
            num_threads: 8
            use_backgrounds: True
            use_monochrome_assets: False
            restrict_themes: False
        train:
            distribution_mode: 'easy'
            seed: 0
            start_level: 0
            num_levels: 100000
        val_sim:
            distribution_mode: 'easy'
            seed: 0
            start_level: 50000
            num_levels: 256
        val_true:
            distribution_mode: 'hard'
            seed: 0
            start_level: 50000
            num_levels: 256
        test:
            distribution_mode: 'hard'
            seed: 0
            start_level: 0
            num_levels: 100000
    cliport:
        common:
            env_name: 'stack-block-pyramid-seq'
            normalize_rew: False
            num_envs: 1
            num_threads: 1
            assets_root: './lib/cliport/cliport/environments/assets'
            disp: False
            shared_memory: False
        train:
            distribution_mode: 'seen'
            seed: 0
            start_level: 0
            num_levels: 100000
        val_sim:
            distribution_mode: 'seen'
            seed: 0
            start_level: 50000
            num_levels: 64
        val_true:
            distribution_mode: 'unseen'
            seed: 0
            start_level: 50000
            num_levels: 64
        test:
            distribution_mode: 'unseen'
            seed: 0
            start_level: 0
            num_levels: 100000
    minigrid:
        common:
            env_name: 'MiniGrid-Dynamic-Obstacles'
            num_envs: 64
            num_threads: 8
        train:
            env_name_suffix: '-6x6-v0'
            seed: 0
        val_sim:
            env_name_suffix: '-6x6-v0'
            seed: 0
        val_true:
            env_name_suffix: '-Random-8x8-v0'
            seed: 0
        test:
            env_name_suffix: '-Random-8x8-v0'
            seed: 0
algorithm:
    always:
        dummy: null
    random:
        cls: RandomAlgorithm
    threshold:
        cls: ThresholdAlgorithm
        min_pct: 0
        max_pct: 101
        pct_step: 10
        num_rollouts: 64
    ppo:
        cls: PPOAlgorithm
        log_freq: 10
        num_steps: 128
        total_timesteps: 25000000
        update_epochs: 3
        gamma: 0.999
        gae_lambda: 0.95
        num_minibatches: 8
        clip_coef: 0.2
        norm_adv: True
        clip_vloss: True
        vf_coef: 0.5
        ent_coef: 0.01
        max_grad_norm: 0.5
        learning_rate: 0.0005
    ood:
        cls: OODAlgorithm
        contamination: 0.1
        use_ae: False
        num_rollouts: 64
        num_thresholds: 10
        epoch: 100
        batch_size: 64
        feature_size: 64