name: "procgen_agent_novice"

env:
  name: "procgen"
  train:
    distribution_mode: "easy"
    seed: 0
    start_level: 0
    num_levels: 100000
  test:
    distribution_mode: "easy"
    seed: 0
    start_level: 0
    num_levels: 100000

algorithm:
  name: "ppo"
  total_timesteps: 15000000

policy:
  name: "ppo"
  model: "impala_ppo"