name: 'procgen_ood'
general:
    benchmark: 'procgen'
    algorithm: 'ood'
    device: 0
    skyline: 0
    seed: 10
coord_policy:
    cls: OODPolicy
    feature_type: 'obs'
    collect_data_agent: 'weak'
