name: 'procgen_skyline'
env:
    suite: 'procgen'
    name: 'coinrun'
    train: 
        distribution_mode: 'hard'
algorithm: 'PPOAlgorithm'
policy: 'PPOPolicy'
coordination:
    expert_query_cost_alpha: 0.4
    switch_agent_cost_beta: 0.0
    act_greedy: False