name: "procgen_ask_every_k"

env:
  name: "procgen"

algorithm:
  name: "ask_every_k"

policy:
  name: "ask_every_k"

train_novice: "experiments/procgen_ppo_novice/best_test.ckpt"
train_expert: "experiments/procgen_ppo_expert/best_test.ckpt"
test_novice: "experiments/procgen_ppo_novice/best_test.ckpt"
test_expert: "experiments/procgen_ppo_expert/best_test.ckpt"