name: 'procgen_ppo_novice'
general:
    benchmark: 'procgen'
    algorithm: 'ppo'
    single_agent: 1
    device: 0
    seed: 10
coord_policy:
    cls: PPOPolicy
    model_cls: ImpalaPolicyModel
    feature_type: 'obs'
algorithm:
    cls: PPOAlgorithm
    log_freq: 10
    num_steps: 256
    total_timesteps: 1500000
    update_epochs: 3
    gamma: 0.999
    gae_lambda: 0.95
    num_minibatches: 8
    clip_coef: 0.2
    norm_adv: True
    clip_vloss: True
    vf_coef: 0.5
    ent_coef: 0.01
    max_grad_norm: 0.5
    learning_rate: 0.0005
environment:
    common:
        env_name: 'coinrun'
        normalize_rew: False
        num_envs: 64
        num_threads: 8
        use_backgrounds: True
        use_monochrome_assets: False
        restrict_themes: False
        splits: ['train', 'test']
    train:
        distribution_mode: 'easy'
        seed: 0
        start_level: 0
        num_levels: 100000
    test:
        distribution_mode: 'easy'
        seed: 0
        start_level: 0
        num_levels: 100000