name: "procgen_random"

env:
  name: "procgen"
  train:
    distribution_mode: "hard"

algorithm:
  name: "random"

policy:
  name: "random"

train_novice: "experiments/procgen_novice/best_test.ckpt"
train_expert: "experiments/procgen_expert/best_test.ckpt"
test_novice: "experiments/procgen_novice/best_test.ckpt"
test_expert: "experiments/procgen_expert/best_test.ckpt"