name: "procgen_ppo_novice"
algorithm:
    cls: "PPOAlgorithm"
    total_timesteps: 15000000
env:
    suite: 'procgen'
    name: 'coinrun'
    train:
        distribution_mode: 'easy'
        seed: 0
        start_level: 0
        num_levels: 100000
    test:
        distribution_mode: 'easy'
        seed: 0
        start_level: 0
        num_levels: 100000
policy:
    cls: 'PPOPolicy'
    model: "ImpalaPPOModel"